# Generated by Django 2.1.1 on 2019-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190515_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_grp',
            field=models.CharField(default='Individual', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_task',
            field=models.CharField(default='', max_length=500),
        ),
    ]
