# Generated by Django 2.1.1 on 2019-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_grp',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_grp',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_task',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Default Name', max_length=500),
        ),
    ]
