# Generated by Django 2.1.1 on 2019-05-15 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190515_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wms_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wms_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
