# Generated by Django 2.1.1 on 2019-05-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190515_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wms_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
