# Generated by Django 2.1.1 on 2019-05-16 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190516_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='curr_grp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curr_grp', to=settings.AUTH_USER_MODEL),
        ),
    ]
