# Generated by Django 2.1.1 on 2019-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190516_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_fn',
            new_name='default_function',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_lead',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='whs_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
