# Generated by Django 2.1.1 on 2019-05-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190516_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curr_grp',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
