# Generated by Django 2.2.1 on 2019-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190517_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_grp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wms_id',
            field=models.IntegerField(default=0),
        ),
    ]
