# Generated by Django 2.2.1 on 2019-06-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190604_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_grp',
        ),
    ]
