# Generated by Django 2.2.1 on 2019-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_current_grp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operator_email',
            field=models.CharField(default='default@shopee.com', max_length=200),
            preserve_default=False,
        ),
    ]
