# Generated by Django 2.1.1 on 2019-05-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='author',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
