# Generated by Django 2.1.1 on 2019-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_auto_20190515_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='wms_id',
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='jiana.xu', max_length=100),
            preserve_default=False,
        ),
    ]
