# Generated by Django 2.1.1 on 2019-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_auto_20190515_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='work_complete',
            field=models.IntegerField(default=0),
        ),
    ]
