# Generated by Django 2.1.1 on 2019-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0010_group_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
