# Generated by Django 2.1.1 on 2019-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0011_auto_20190517_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='work_complete',
            field=models.CharField(max_length=100),
        ),
    ]
