# Generated by Django 2.1.1 on 2019-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0012_auto_20190520_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='action',
            field=models.CharField(default='Start', max_length=100),
            preserve_default=False,
        ),
    ]
