# Generated by Django 2.1.1 on 2019-05-23 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0013_post_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
