# Generated by Django 2.1.1 on 2019-05-23 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0014_auto_20190524_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 16, 52, 3, 384081, tzinfo=utc)),
        ),
    ]
