# Generated by Django 2.1.1 on 2019-05-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0015_auto_20190524_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
