# Generated by Django 2.2.1 on 2019-05-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0016_auto_20190524_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='New Group', max_length=500),
        ),
    ]
