# Generated by Django 2.2.1 on 2019-05-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0017_group_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
    ]
