# Generated by Django 2.2.1 on 2019-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0018_remove_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='members',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
