# Generated by Django 2.2.1 on 2019-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0019_post_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('IB', 'Inbound'), ('OB', 'Outbound'), ('INV', 'Inventory'), ('UN', 'Unspecified')], default='UN', max_length=100)),
                ('task_name', models.TextField()),
                ('output_record', models.BooleanField(default=0)),
            ],
        ),
    ]
