# Generated by Django 2.2.1 on 2019-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0020_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('IB', 'Inbound'), ('OB', 'Outbound'), ('INV', 'Inventory'), ('UN', 'Unspecified')], default='UN', max_length=3),
        ),
    ]
