# Generated by Django 2.2.1 on 2019-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0021_auto_20190531_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='whs_id',
            field=models.CharField(choices=[('MYL', 'MYL'), ('THA', 'THA'), ('VNN', 'VNN'), ('UN', 'Unspecified')], default='UN', max_length=3),
        ),
    ]
