# Generated by Django 2.1.1 on 2019-05-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190515_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_fn',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_grp',
            field=models.CharField(default='Individual', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='blank', max_length=500),
        ),
    ]
